inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

RSpec/DescribedClass:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/IfUnlessModifier:
  Enabled: false
