Layout/HeredocIndentation:
  Exclude:
    - 'lib/circleci/bundle/update/pr.rb'

# See also https://github.com/masutaka/circleci-bundle-update-pr/issues/84
Style/FrozenStringLiteralComment:
  Exclude:
    - 'lib/circleci/bundle/update/pr.rb'
